#pragma once

class CPEINFO
{
public:
	CPEINFO();
	~CPEINFO();
	//PIMAGE_NT_HEADERS32 pNtH;	//NT头
	//PIMAGE_NT_HEADERS64 pNtH64;	//NT头64
	PIMAGE_NT_HEADERS pNt=NULL;	//NT头

	IMAGE_FILE_HEADER* m_pFileHdr;		//文件头
	//PIMAGE_OPTIONAL_HEADER32 pOptH;//可选头
	//PIMAGE_OPTIONAL_HEADER64 pOptH64;//64位的可选PE头
	PIMAGE_SECTION_HEADER pSection=NULL;//区段头
	PIMAGE_DATA_DIRECTORY pDirectory=NULL;//数据目录
	PIMAGE_EXPORT_DIRECTORY pExport=NULL;// 导出表数据
	PIMAGE_IMPORT_DESCRIPTOR pImport = NULL;
	PIMAGE_RESOURCE_DIRECTORY pResource = NULL;
	PIMAGE_BASE_RELOCATION pRelocal = NULL;
	PIMAGE_TLS_DIRECTORY pTLS = NULL;
	PIMAGE_DELAYLOAD_DESCRIPTOR pDelay = NULL;
	unsigned char* buff;

	DWORD Rva2Foa(DWORD dwRva);
	CString GetSection(DWORD dwRva);
	
};

